name: Deploy Watashi Server To cPanel

on:
  push:
    branches: [master]
    paths:
      - "server/**"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: ./server

      - name: Generate build
        run: npm run build
        working-directory: ./server

      - name: Upload dist folder
        uses: actions/upload-artifact@v4
        with:
          name: dist_folder
          path: server/dist/

  upload:
    name: ðŸŽ‰ Deploy
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Creating restart file
        run: |
          mkdir tmp && touch tmp/restart.txt 
          echo $RANDOM > tmp/restart.txt
        working-directory: ./server

      - name: download dist folder
        uses: actions/download-artifact@v4
        with:
          name: dist_folder
          path: server/dist/

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./server/
          exclude: |
            **/.git/**
            **/.github/**
            **/node_modules/
            **/*.md
            .env
            .env.*
            .gitignore
            .eslintrc.json
            nest-cli.json
            test/**
            src/**
            *.spec.ts
